
spring:
  application:
    name: ms-tuti-cloud-client

server:
  port: ${SERVER_PORT_CLIENT:8084}
      
grpc:
  client:
    ms-tuti-server:
      address: 'static://127.0.0.1:50051'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    ms-tuti-serent:
      address: 'static://127.0.0.1:50053'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    ms-tuti-cloud-server:
      address: 'discovery:///ms-tuti-cloud-server'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext  
    ms-tuti-server-reactive:
      address: 'static://127.0.0.1:50055'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
 